Вторая практическая работа
Mixail999/ono-tebe-nado pull request #1
Opened 2024-02-29 13:51 UTC by Mixail999

Отправляю на ревью (попытка 1).

2024-02-29 14:33 UTC, Savallera requested changes
## Здравствуйте! У Вас отличная работа, что отметила

### Положительные моменты:

* Все комментарии в коде с пометкой **Отлично**
* Проект визуально соответствует макету
* Файловая структура проекта единообразна
* Валидный HTML и CSS, нет ошибок в консоли
* Аккуратное форматирование кода
* Используется семантическая разметка
* Соблюдены требования к именованию CSS классов
* Для организации лейаута ключевых блоков использован `flex/grid`

### Что требует доработки:

* Все комментарии в коде с пометкой **Надо исправить**
* Для реализации заголовка по макету следует использовать выравнивание текста у спанов через класс `align-text`, а также межбуквенное расстояние `letter-spacing` по макету, вместо жестких отступов.

### Что можно сделать лучше:

* Все комментарии в коде с пометкой **Можно лучше**

### Полезности для Вас

* [Лучший способ реализовать «обёртки» в CSS](https://css-live.ru/articles/luchshij-sposob-realizovat-obyortki-v-css.html)
* [Универсальный строительный блок без семантического значения.](https://doka.guide/html/div/)
* [Ссылки — это то, что делает интернет настоящей паутиной](https://doka.guide/html/a/)
* [Атрибуты Alt и Title для картинок](https://siteclinic.ru/blog/internal-optimization/atributy-alt-i-title/)
* [CSS: использование внутренних и внешних отступов](https://habr.com/ru/companies/ruvds/articles/499120/)
* [Когда использовать флексы, а когда гриды](https://htmlacademy.ru/blog/css/flexbox-vs-grid)

---

Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены, **основные требования соответствуют брифу и чек листу**. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

---

Перед отправкой работы проверьте разметку в валидаторе на отсутствие Error https://validator.w3.org

---

Комментарии **Надо исправить** обязательны для исправления, работа будет зачтена после исправления всех таких комментариев.
Комментарии **Можно лучше** носят рекомендательный характер, их выполнение остается на Ваше усмотрение.

---

**У Вас все получится! Желаю удачного дня!**

2024-02-29 14:33 UTC, Savallera commented on index.html
>    </head>
**Отлично**
   Корректно задан `viewport`, прописан `title` в `head`.

2024-02-29 14:33 UTC, Savallera commented on index.html
> +      <nav class="header__menu">
**Отлично**
         Обертка для данных элементов - тег `nav`

2024-02-29 14:33 UTC, Savallera commented on index.html
> +      <div class="header__logo">
**Можно лучше**
         Этот элемент - лишняя обертка. Её можно удалить без вреда для верстки. Старайтесь избегать лишних элементов в разметке.

2024-02-29 14:33 UTC, Savallera commented on index.html
> +        <p>
**Можно лучше**
            Ссылки также относятся к семантическому селектору, оборачивать их параграфом необязательно. Если необходимо добавьте им блочную модель и укажите ширину по контенту `max-content`

2024-02-29 14:33 UTC, Savallera commented on index.html
> +        <p>наб. Принсенграхт 263-<br />265, Амстердам</p>
**Можно лучше** Вместо жесткого переноса хорошо добавить сво-во ограничения по максимальной ширине всему блоку с адресом `max-width`, это позволит сделать мягкие переносы.

2024-02-29 14:33 UTC, Savallera commented on index.html
> +    <main>
**Отлично** 
       Контентное содержимое обёрнуто тегом `main`

2024-02-29 14:33 UTC, Savallera commented on index.html
> +            <article class="card card_type_film">
**Отлично** Используется селектор артикля для карточки

2024-02-29 14:33 UTC, Savallera commented on index.html
> +        <div class="about__logo">
**Можно лучше**
           Этот элемент - лишняя обертка. Её можно удалить без вреда для верстки. Старайтесь избегать лишних элементов в разметке.

2024-02-29 14:33 UTC, Savallera commented on index.html
> +    <address class="address">
**Отлично** Блок с адресом используется повторно в подвале.

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +.header__links-list-item_no-bullit {
**Можно лучше** 
   Когда нужно обратится к элементам по их порядковому номеру на помощь приходят [псевдоклассы](https://doka.guide/css/child/). С их помощью хорошо уточнить стилизацию, например, удалить первый буллит, добавить отступ между одинаковыми элементами, расположить фото в галерее и т.д.

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +.header__link_active {
**Можно лучше** 
 Активной ссылке/кнопке хорошо заблокировать отображение курсора и предотвратить переход по щелчку - рассмотрите сво-во pointer-events https://doka.guide/css/pointer-events/

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +    width: 239px;
**Можно лучше** 
     Жёсткое ограничение ширины - это не лучший способ строить сайт. Потому что в таком случае появятся проблемы с адаптацией под мобильные и планшеты: ширина экрана может быть меньше ширины блока. Тогда часть сайта будет выходить пределы вёрстки сайта и появится горизонтальная прокрутка, чего у версии сайта на мобильном быть не должно. Поэтому вместо жёсткого задания ширины используется ограничение сверху через CSS свойство `max-width`. 
     Мы знаем, что блочный элемент `div` пытается занять всю ширину родительского элемента, как будто по-умолчанию у него есть свойство `width` и оно имеет значение 100%. 
     
     https://www.mousedc.ru/learning/13-shirina-width-vysota-height-html/

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +    text-underline-offset: 4px;
**Надо исправить** Данное описание носит глобальный характер. Хорошо его перенести в селектор `a` в файле сбросов `globals.css`

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +    z-index: 0;
**Можно лучше** 
     Когда нужно, чтобы элемент находился под другими элементами блока, можно воспользоваться таким подходом: 
    
     1. блок поднимите по оси Z вверх `z-index: 1` 
     2. элементы, которые должны находится под текстом опустите по оси Z `z-index: -1`.  
     [Больше про контекст наложения](https://medium.com/nuances-of-programming/объясняем-z-index-как-позиционировать-элементы-с-помощью-css-e80bc85cf36c)

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +    margin-bottom: 20px;
**Можно лучше** 
      Для равномерного распределения элементов, хорошо воспользоваться свойством [`gap` для `flex` блоков](https://webformyself.com/ponimanie-gap-v-css/)

2024-02-29 14:33 UTC, Savallera commented on styles/style.css
> +    padding-left: 585px;
**Надо исправить**
Для реализации заголовка по макету следует использовать выравнивание текста у спанов через класс `align-text`, а также межбуквенное расстояние `letter-spacing` по макету, вместо жестких отступов.

Обратите внимание на оформление букв по макету https://yadi.sk/d/CnSQ9Fka2fetVw

2024-03-01 13:08 UTC, Mixail999 commented
Попытка №2

2024-03-01 13:40 UTC, Savallera approved these changes
## Здравствуйте! Спасибо, что уделили внимание комментариям и внесли исправления.

Хорошая работа по замечаниям, отметила моменты, которые требуют еще доработки.

### Что требует доработки:

* Все комментарии в коде с пометкой **Надо исправить**
* Спан в третьем слове оказался пустой, из-за этого есть отклонения по макету
* В секции с карточками добавьте перенос новой карточки в следующий ряд, т.к. этот блок динамичный, хорошо предусмотреть возможность наполнения его большим кол-вом карточек.

---

Ваша работа принимается на второй итерации. Желаю успехов в следующих спринтах :)

### Полезности для Вас

**Настройка редактора кода**

- [Форматирование кода](https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code-ru)
- Перевод рекомендаций Google [по форматированию кода](https://habr.com/ru/post/143452/)
- Секретные хаки [VS Code](https://habr.com/ru/post/435770/)
- [Emmet](https://emmet.io/)
- Справочник по сокращениям [Emmet](https://webdesign-master.ru/blog/html-css/2.html)
- Подборка [плагинов для VS Code](https://techrocks.ru/2019/02/17/20-vs-code-extensions/)
- Еще одна подборка [плагинов для VS Code](https://techrocks.ru/2019/03/31/vs-code-customization/)

**HTML**

- Небольшая [лекция по тегам](https://github.com/Max-Starling/Notes/blob/master/HTML.md), какие они бывают
- Проконтролируй себя в [валидаторе](https://validator.w3.org/#validate_by_input)

**Naming**

- Часто используемые [слова в классах](https://github.com/yoksel/common-words)

**Игрушки для изучения Flex**

- [http://www.flexboxdefense.com/](http://www.flexboxdefense.com/)
- [http://flexboxfroggy.com/#ru](http://flexboxfroggy.com/#ru)

2024-03-01 13:40 UTC, Savallera commented on index.html
> +            О<span class="letter-spacing-60">но</span>
**Надо исправить** В именовании редко когда используются цифровые обозначения, старайтесь их избегать, для именования хорошо использовать популярные именования (sm, md, lg, expanded, normal, и т.д.). Таким образом Вы обезопасите себя от четкой фиксации к цифре - 60пх может легко смениться на 55 45 75 и т.д. 

`letter-spacing-expanded, letter-spacing-normal`

2024-03-01 13:40 UTC, Savallera commented on index.html
> +          <span class="accent-span text-right"></span>
**Надо исправить** Оберните все слово `НАДО` селектором спан с классом `accent-span text-right` https://yadi.sk/d/GqYdW6i-3BIn8g

2024-03-01 13:40 UTC, Savallera commented on styles/style.css
> +  display: flex;
**Надо исправить** Добавьте возможность переноса карточки на новую строку, хорошо подойдет сво-во `flex-wrap` для переноса https://yadi.sk/d/nhVhJmOF3AI_Bw

2024-03-01 14:57 UTC, merged